#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Make Thunar always launched with DBUS
# Without this, mounting, unmounting, trash, etc won't work in Thunar
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS";
then
	eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Make sure this is before the 'exec' command or it won't be sourced.
#[ -f /etc/xprofile ] && . /etc/xprofile
#[ -f ~/.xprofile ] && . ~/.xprofile

#run polkit to authentication app that need root priveleges
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#notification daemon for earlyoom
systembus-notify &
#X hotkey daemon
sxhkd &
#$HOME/.local/bin/tumblerd.sh &
#disable touchpad while typing
syndaemon -i 1 -t -K -R -d
#hide cursor when not needed
unclutter --timeout 10 &
#compositor
(sleep 3 && picom --experimental-backends) &
#wallpaper setter
nitrogen --restore &
#polybar moved to openbox autostart
#$HOME/.config/polybar/launch.sh
#sleep 3 && flameshot &
#Clipboard manager
(sleep 4s && parcellite) &
#xautolock -time 10 -detectsleep -locker "$HOME/.local/bin/myfancy -n -t 'Screen Locked'" &
#xautolock -time 15 -locker lock.sh &
#$HOME/suckless/dwm-bar/dwm_bar.sh &
# Here openbox is kept as default
session=${1:-openbox}

case $session in
    i3|i3wm           ) exec i3;;
    openbox           ) exec openbox-session;;
    dwm        		  ) exec dwm;;
    # No known session, try to run it as command
    *                 ) exec $1;;
esac
